#! /usr/bin/env python3

from pathlib import Path
import sys

metaarm = Path.cwd()

if metaarm.name != "meta-arm":
    print("Not running inside meta-arm")
    sys.exit(1)

# All machine configurations
machines = metaarm.glob("meta-*/conf/machine/*.conf")
machines = set(p.stem for p in machines)

# All kas files
kas = metaarm.glob("kas/*.yml")
kas = set(p.stem for p in kas)

missing = machines - kas
print(f"The following machines are missing: {', '.join(sorted(missing))}.")

covered = len(machines) - len(missing)
total = len(machines)
percent = int(covered / total * 100)
print(f"Coverage: {percent}%")
